[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2024"
name = "napi-escape"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.12.4", default-features = false, features = ["napi3"] }
napi-derive = { version = "3.6.5", default-features = false, features = [
  "type-def",
] }
html-escape-simd = "0.1"

[target.'cfg(all(not(target_os = "linux"), not(target_family = "wasm")))'.dependencies]
mimalloc-safe = { version = "0.1.66", features = ["skip_collect_on_exit"] }

[target.'cfg(target_os = "linux")'.dependencies]
mimalloc-safe = { version = "0.1.66", features = ["local_dynamic_tls", "skip_collect_on_exit"] }

[build-dependencies]
napi-build = "2.4.2"

[profile.release]
lto = true
opt-level = 3
