/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function asyncEscapeHTMLBuf(input: Uint8Array, signal?: AbortSignal | undefined | null): Promise<string>

export declare function escapeHTML(input: string): string

export declare function escapeHTMLBuf(input: Uint8Array): string
