/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function escapeHTML(input: string): string
export function escapeHTMLBuf(input: Buffer): string
export function asyncEscapeHTMLBuf(input: Buffer, signal?: AbortSignal | undefined | null): Promise<string>
